platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project 'Example.xcodeproj'

install! 'cocoapods', :deterministic_uuids => false

def pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  use_frameworks!
  
end

target 'Example' do
  pods
end

